export const data = [
  {
    id: 1,
    icon: "/public/foundationIcon.jfif",
    foundation: "Reed Foundation",
    name: "Food distribution for kids in lagos",
    image: "/public/foundationImg.jfif",
    people: 250,
    daysLeft: 19,
    currAmount: 50000,
    totalAmount: 170000,
  },
  {
    id: 2,
    icon: "/public/foundationIcon.jfif",
    foundation: "Reed Foundation",
    name: "Food distribution for kids in lagos",
    image: "/public/foundationImg.jfif",
    people: 250,
    daysLeft: 19,
    currAmount: 70000,
    totalAmount: 80000,
  },
  {
    id: 3,
    icon: "/public/foundationIcon.jfif",
    foundation: "Reed Foundation",
    name: "Food distribution for kids in lagos",
    image: "/public/foundationImg.jfif",
    people: 250,
    daysLeft: 19,
    currAmount: 350000,
    totalAmount: 600000,
  },
  {
    id: 4,
    icon: "/public/foundationIcon.jfif",
    foundation: "Reed Foundation",
    name: "Food distribution for kids in lagos",
    image: "/public/foundationImg.jfif",
    people: 250,
    daysLeft: 19,
    currAmount: 70000,
    totalAmount: 120000,
  },
  {
    id: 5,
    icon: "/public/foundationIcon.jfif",
    foundation: "Reed Foundation",
    name: "Food distribution for kids in lagos",
    image: "/public/foundationImg.jfif",
    people: 250,
    daysLeft: 19,
    currAmount: 70000,
    totalAmount: 190000,
  },
  {
    id: 6,
    icon: "/public/foundationIcon.jfif",
    foundation: "Reed Foundation",
    name: "Food distribution for kids in lagos",
    image: "/public/foundationImg.jfif",
    people: 250,
    daysLeft: 19,
    currAmount: 70000,
    totalAmount: 180000,
  },
  {
    id: 7,
    icon: "/public/foundationIcon.jfif",
    foundation: "Reed Foundation",
    name: "Food distribution for kids in lagos",
    image: "/public/foundationImg.jfif",
    people: 250,
    daysLeft: 19,
    currAmount: 30000,
    totalAmount: 170000,
  },
];

export const donations = [
  {
    id: 1,
    name: "Anonymous",
    amount: 70000,
    days: 1,
  },
  {
    id: 2,
    name: "Ken",
    amount: 100000,
    days: 2,
  },
  {
    id: 3,
    name: "Prosper",
    amount: 60000,
    days: 2,
  },
];
