export const CharityList = [
  {
    id: 1,
    title: "Food distribution for kids in lagos",
    initial: 70000,
    initialDispalyed: "N70,000",
    goal: 170000,
    goalDisplayed: "N170,000",
    progress: `40%`,
  },
  {
    id: 2,
    title: "Indomie distribution for kids in lagos",
    initial: 10000,
    goal: 50000,
    initialDispalyed: "10 cartons",
    goalDisplayed: "50 cartons",
    progress: `${Math.round((10 / 50) * 100)}%`,
  },
  {
    id: 3,
    title: "Food distribution for kids in lagos",
    initial: 70000,
    initialDispalyed: "N70,000",
    goal: 170000,
    goalDisplayed: "N170,000",
    progress: `40%`,
  },
  {
    id: 4,
    title: "Indomie distribution for kids in lagos",
    initial: 10000,
    initialDispalyed: "10 cartons",
    goal: 50000,
    goalDisplayed: "50 cartons",
    progress: `${Math.round((10 / 50) * 100)}%`,
  },
];

const data = [
  {
    id: 1,
    icon: "/public/foundationIcon.jfif",
    foundation: "Reed Foundation",
    name: "Food distribution for kids in lagos",
    image: "/public/foundationImg.jfif",
    people: 250,
    daysLeft: 19,
    currAmount: 70000,
    totalAmount: 170000,
    initialDispalyed: "N70,000",
    goalDisplayed: "N170,000",
  },
  {
    id: 2,
    icon: "/public/foundationIcon.jfif",
    foundation: "Reed Foundation",
    name: "Food distribution for kids in lagos",
    image: "/public/foundationImg.jfif",
    people: 250,
    daysLeft: 19,
    currAmount: 10,
    totalAmount: 50,
    initialDispalyed: "10 cartons",
    goalDisplayed: "50 cartons",
  },
  {
    id: 3,
    icon: "/public/foundationIcon.jfif",
    foundation: "Reed Foundation",
    name: "Food distribution for kids in lagos",
    image: "/public/foundationImg.jfif",
    people: 250,
    daysLeft: 19,
    currAmount: 350000,
    totalAmount: 600000,
    initialDispalyed: "N350,000",
    goalDisplayed: "N600,000",
  },
  {
    id: 4,
    icon: "/public/foundationIcon.jfif",
    foundation: "Reed Foundation",
    name: "Food distribution for kids in lagos",
    image: "/public/foundationImg.jfif",
    people: 250,
    daysLeft: 19,
    currAmount: 10,
    totalAmount: 50,
    initialDispalyed: "10 cartons",
    goalDisplayed: "50 cartons",
  },
  {
    id: 5,
    icon: "/public/foundationIcon.jfif",
    foundation: "Reed Foundation",
    name: "Food distribution for kids in lagos",
    image: "/public/foundationImg.jfif",
    people: 250,
    daysLeft: 19,
    currAmount: 70000,
    totalAmount: 170000,
    initialDispalyed: "N70,000",
    goalDisplayed: "N170,000",
  },
];

export default data